#!/usr/bin/env bash

source configure_paths.sh

m4 -DTEMPLATE_LLVM_CONFIG_BIN=${LLVM_CONFIG_BIN} -DTEMPLATE_ISL_INCLUDE=$ISL_INCLUDE_DIRECTORY \
   -DTEMPLATE_ISL_LIB=$ISL_LIB_DIRECTORY -DTEMPLATE_HALIDE=$HALIDE_SOURCE_DIRECTORY \
   -DTEMPLATE_HALIDE_LIB=$HALIDE_LIB_DIRECTORY -DTEMPLATE_MKL=$MKL_PREFIX \
   templates/configure_path.cmake.m4 > configure_path.cmake
