name: cost_model_env
channels:
  - pytorch
  - defaults
  - anaconda
dependencies:
  - cudatoolkit=11.3.1
  - python=3.10.6
  - pytorch=1.12.1
  - scipy==1.9.1
  - numpy==1.22.3
  - pandas==1.4.2
  - scikit-learn==1.1.2
  - pip:
    - hydra-core==1.1.2
    - tqdm==4.59.0
    - wandb==0.12.15



