set(LLVM_CONFIG_BIN "TEMPLATE_LLVM_CONFIG_BIN")


set(ISL_INCLUDE_DIRECTORY "TEMPLATE_ISL_INCLUDE")
set(ISL_LIB_DIRECTORY "TEMPLATE_ISL_LIB")
set(HALIDE_SOURCE_DIRECTORY "TEMPLATE_HALIDE")
set(HALIDE_LIB_DIRECTORY "TEMPLATE_HALIDE_LIB")

set(MKL_PREFIX "TEMPLATE_MKL")
